/**
 * MODEL — conditions.js
 * Fonte única de verdade para todas as condições de saúde mental.
 * Nenhuma view ou controller deve definir dados de condição diretamente.
 */

const CONDITIONS = [
  {
    id: "ansiedade",
    label: "Ansiedade",
    title: "Transtorno de Ansiedade",
    description:
      "A ansiedade é uma resposta natural do corpo ao estresse. Torna-se um transtorno quando é excessiva, persistente e interfere na vida cotidiana.",
    commonSymptoms: [
      "Preocupação excessiva e constante",
      "Coração acelerado (taquicardia)",
      "Dificuldade para dormir",
      "Tensão muscular",
      "Falta de ar",
    ],
    rareSymptoms: [
      "Dores de estômago sem causa médica",
      "Dificuldade de concentração",
      "Sensação de irrealidade",
      "Formigamentos no corpo",
      "Evitar situações sociais simples",
    ],
    causes: [
      "Genética",
      "Estresse crônico",
      "Traumas passados",
      "Desequilíbrio hormonal",
      "Fatores ambientais",
      "Uso de substâncias",
    ],
    quickSub: "Preocupação excessiva, crises e medos",
  },
  {
    id: "depressao",
    label: "Depressão",
    title: "Depressão",
    description:
      "Mais do que tristeza, a depressão é um transtorno do humor que afeta o pensamento, o comportamento e a saúde física. É tratável e reconhecê-la é o primeiro passo.",
    commonSymptoms: [
      "Tristeza profunda e persistente",
      "Perda de interesse em atividades",
      "Fadiga extrema",
      "Mudanças no sono",
      "Sentimento de inutilidade",
    ],
    rareSymptoms: [
      "Irritabilidade sem motivo claro",
      "Dores físicas inexplicáveis",
      "Dificuldade em decisões simples",
      "Isolamento sem perceber",
      "Alterações intensas de apetite",
    ],
    causes: [
      "Histórico familiar",
      "Perdas e lutos",
      "Isolamento social",
      "Desequilíbrio químico",
      "Doenças crônicas",
      "Estresse prolongado",
    ],
    quickSub: "Tristeza profunda, desânimo e apatia",
  },
  {
    id: "burnout",
    label: "Burnout",
    title: "Burnout",
    description:
      "Síndrome de esgotamento profissional causada por estresse crônico no trabalho. Reconhecida pela OMS como fenômeno ocupacional desde 2019.",
    commonSymptoms: [
      "Exaustão extrema mesmo após descanso",
      "Cinismo em relação ao trabalho",
      "Queda de produtividade",
      "Dores de cabeça frequentes",
      "Dificuldade de desligar do trabalho",
    ],
    rareSymptoms: [
      "Sensação de fracasso constante",
      "Despersonalização (sentir-se robô)",
      "Alterações imunológicas frequentes",
      "Esquecimento e confusão mental",
      "Distanciamento de pessoas próximas",
    ],
    causes: [
      "Sobrecarga de trabalho",
      "Falta de reconhecimento",
      "Ambiente tóxico",
      "Falta de controle",
      "Perfeccionismo",
      "Ausência de pausas",
    ],
    quickSub: "Esgotamento emocional",
  },
  {
    id: "toc",
    label: "TOC",
    title: "TOC — Transtorno Obsessivo-Compulsivo",
    description:
      "Caracterizado por pensamentos intrusivos e repetitivos (obsessões) e comportamentos rituais (compulsões) realizados para aliviar a ansiedade gerada por esses pensamentos.",
    commonSymptoms: [
      "Medo de contaminação ou sujeira",
      "Verificações repetidas",
      "Necessidade de simetria e ordem",
      "Pensamentos intrusivos indesejados",
      "Rituais mentais (contar, rezar)",
    ],
    rareSymptoms: [
      "Dúvida excessiva de si mesmo",
      "Medo de machucar sem querer",
      "Dificuldade em descartar objetos",
      "Busca excessiva por reasseguramento",
      "Perfeccionismo paralisante",
    ],
    causes: [
      "Predisposição genética",
      "Disfunção em circuitos cerebrais",
      "Eventos traumáticos",
      "Fatores ambientais",
      "PANDAS (em crianças)",
    ],
    quickSub: "Transtorno obsessivo-compulsivo",
  },
  {
    id: "panico",
    label: "Pânico",
    title: "Síndrome do Pânico",
    description:
      "A síndrome do pânico é marcada por episódios súbitos e intensos de medo extremo — as crises de pânico — que ativam respostas físicas severas mesmo sem perigo real.",
    commonSymptoms: [
      "Batimento cardíaco acelerado (taquicardia)",
      "Sensação de sufocamento ou falta de ar",
      "Tremores e sudorese intensa",
      "Tontura e sensação de desmaio",
      "Medo intenso de morrer ou enlouquecer",
    ],
    rareSymptoms: [
      "Formigamento nas extremidades",
      "Náusea e dor abdominal durante a crise",
      "Despersonalização (sentir-se fora do corpo)",
      "Evitação de locais por medo de nova crise",
      "Ansiedade antecipatória persistente",
    ],
    causes: [
      "Predisposição genética",
      "Estresse elevado",
      "Experiências traumáticas",
      "Desequilíbrio de neurotransmissores",
      "Consumo de cafeína/estimulantes",
    ],
    quickSub: "Crises, gatilhos e causas",
  },
  {
    id: "tept",
    label: "TEPT",
    title: "Transtorno de Estresse Pós-Traumático (TEPT)",
    description:
      "O TEPT se desenvolve após a exposição a eventos traumáticos graves. A pessoa revive o trauma de forma intrusiva, mesmo muito depois de o evento ter ocorrido.",
    commonSymptoms: [
      "Flashbacks e memórias intrusivas do trauma",
      "Pesadelos recorrentes",
      "Evitação de situações que lembrem o trauma",
      "Hipervigilância e sobressalto fácil",
      "Dificuldade para dormir",
    ],
    rareSymptoms: [
      "Entorpecimento emocional e distanciamento",
      "Memória fragmentada do evento traumático",
      "Sentimento de culpa ou vergonha excessivos",
      "Irritabilidade e comportamentos autodestrutivos",
      "Sensação de futuro encurtado",
    ],
    causes: [
      "Acidentes graves",
      "Violência física ou sexual",
      "Guerras e conflitos",
      "Perda súbita de ente querido",
      "Desastres naturais",
      "Abuso na infância",
    ],
    quickSub: "Estresse pós-traumático",
  },
  {
    id: "fobias",
    label: "Fobias",
    title: "Fobias",
    description:
      "Fobias são medos intensos, irracionais e persistentes de objetos, situações ou animais específicos. A pessoa reconhece que o medo é excessivo, mas não consegue controlá-lo.",
    commonSymptoms: [
      "Medo imediato e intenso ao confrontar o gatilho",
      "Evitação ativa da situação temida",
      "Ansiedade antecipatória intensa",
      "Reações físicas (suor, tremor, taquicardia)",
      "Interferência significativa na rotina",
    ],
    rareSymptoms: [
      "Fobia social: medo de julgamento em interações",
      "Agorafobia: medo de espaços públicos ou abertos",
      "Fobia de doenças (hipocondria fóbica)",
      "Medo de engolir ou vomitar (fagofobia)",
      "Ataques de pânico desencadeados pelo gatilho",
    ],
    causes: [
      "Experiência traumática com o objeto",
      "Aprendizado por observação",
      "Fatores genéticos",
      "Temperamento ansioso",
      "Condicionamento negativo",
    ],
    quickSub: "Medos intensos e irracionais",
  },
  {
    id: "alimentar",
    label: "T. Alimentares",
    title: "Transtornos Alimentares",
    description:
      "São condições que afetam a relação da pessoa com a comida, o peso e a imagem corporal. Incluem anorexia, bulimia e transtorno de compulsão alimentar, entre outros.",
    commonSymptoms: [
      "Preocupação excessiva com peso e alimentação",
      "Restrição alimentar severa (anorexia)",
      "Episódios de compulsão seguidos de purga (bulimia)",
      "Distorção da imagem corporal",
      "Rituais alimentares rígidos",
    ],
    rareSymptoms: [
      'Ortorexia: obsessão por alimentação "saudável"',
      "Evitação de alimentos por textura ou cor",
      "Isolamento social em refeições",
      "Problemas dentários e esofágicos (purga)",
      "Amenorreia (ausência de menstruação)",
    ],
    causes: [
      "Pressão estética e social",
      "Baixa autoestima",
      "Histórico de traumas",
      "Perfeccionismo",
      "Predisposição genética",
      "Influência midiática",
    ],
    quickSub: "Anorexia, bulimia e outros",
  },
  {
    id: "sono",
    label: "Dist. do Sono",
    title: "Distúrbios do Sono",
    description:
      "Os distúrbios do sono afetam a qualidade, duração e regularidade do sono, comprometendo a saúde física e mental. Incluem insônia, apneia, narcolepsia e parassonias.",
    commonSymptoms: [
      "Dificuldade para adormecer ou manter o sono",
      "Sonolência excessiva durante o dia",
      "Acordar muito cedo sem conseguir voltar a dormir",
      "Sono não restaurador (cansa ao acordar)",
      "Ronco intenso e pausas na respiração",
    ],
    rareSymptoms: [
      "Sonambulismo e falar dormindo",
      "Paralisia do sono com alucinações",
      "Síndrome das pernas inquietas",
      "Bruxismo (ranger de dentes durante o sono)",
      "Cataplexia (perda súbita de tônus muscular)",
    ],
    causes: [
      "Estresse e ansiedade",
      "Higiene do sono inadequada",
      "Uso de telas à noite",
      "Obesidade (apneia)",
      "Doenças crônicas",
      "Uso de álcool ou cafeína",
    ],
    quickSub: "Insônia, apneia e parassonias",
  },
];
